### ISSUE TITLE
Dock LEDs still flashing with brightness set to 0 (As of Remote FW 1.2)

### ISSUE THREAD

**Issue by smarthomesydney** [unfoldedcircle/feature-and-bug-tracker#51] opened 2023-09-21 11:17 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Dock front led flashing white at full brightness when remote charging.   
Even when Dock LEDs set to zero in Configurator/remote dock settings. 

Dock firmware v .92
Remote firmware v 1.2.1

Not a problem in living room, but very annoying when the remote is charging at night in the bedroom. 

Only happening since updating remote to 1.2.1
🤟

### How to Reproduce

Set dock brightness slider to zero.

Dock remote to charge at night in dark room.

Dock front LED will flash white at full brightness

### Expected behavior

Prior to FW 1.2 release and flash. Remote would not flash white when the remote was docked and Dock brightness was set to zero

### System version

1.2.1

### What part of the system affected by the problem?

Overall system

**Comment by smarthomesydney** [comment] 2023-09-23 07:36
Dock firmware updates to.92 and factory reset.  
No difference. 
Remote shows an error after an extended period of time and dock still flashes white when charging with led brightness set to zero.

Will get core error logs for you soon

**Comment by smarthomesydney** [comment] 2023-09-23 08:06
2023-09-23 07:57:25.829519 +00:00	core	NOTICE	Check OTA server for dock firmware update: UC-Dock-XOXOXOXOXOXOXOX
2023-09-23 07:57:21.960800 +00:00	core	NOTICE	[UC-Dock-XOXOXOXOXOXOXOX] SessionAuthenticated msg
2023-09-23 07:57:21.959970 +00:00	core	NOTICE	[UC-Dock-XOXOXOXOXOXOXOX] Session state change: Authenticated
2023-09-23 07:57:21.671843 +00:00	core	NOTICE	[UC-Dock-XOXOXOXOXOXOXOX] Connected to: ws://192.168.1.71:946/
2023-09-23 07:57:20.858775 +00:00	core	NOTICE	[UC-Dock-XOXOXOXOXOXOXOX] Reconnecting in: 500ms
2023-09-23 07:57:20.857055 +00:00	core	NOTICE	[UC-Dock-XOXOXOXOXOXOXOX] on_session_disconnected: ClientDisconnect
2023-09-23 07:57:20.856058 +00:00	core	NOTICE	[UC-Dock-XOXOXOXOXOXOXOX] Session state change: Disconnected
2023-09-23 07:57:20.847492 +00:00	core	ERROR	[UC-Dock-XOXOXOXOXOXOXOX] Websocket server heartbeat failed, disconnecting!
2023-09-23 07:56:45.461027 +00:00	core	NOTICE	Check OTA server for dock firmware update: UC-Dock-XOXOXOXOXOXOXOX

**Comment by smarthomesydney** [comment] 2023-09-23 08:09
Above logs are from me pressing check for dock update on configurator, setting brightness to 0 (zero) on slider and then pressing check for update on the configurator a second time.

As you can see "Websocket server heartbeat failed" error, hence I believe there is a bug in the code between remote and dock ;-)

**Comment by F4Ck0R** [comment] 2023-10-08 09:14
Can confirm, also not working for me.

Remote version 1.3.3
Dock version 0.9.2

**Comment by zehnm** [comment] 2023-11-07 20:03
I can't reproduce this with Dock FW 0.9.2 and brightness set to 0 in web-configurator:
- breathing pattern while charging is no longer shown, status LED remains dark

@martonborzak could you please retest this as well?

Please note that certain error notifications are still shown, even with brightness 0, e.g. if WiFi connection fails. 

We will consider a complete "status LED off" setting.

**Comment by smarthomesydney** [comment] 2023-11-13 02:42
Hi @zehnm 

Remote version 1.4.5
Dock version 0.9.2

I tried resetting both docks and pairing again with both running 0.9.2 and again they still both have breathing pattern (about once every1-2 seconds) when the remote is charging.

I also factory reset the remote and same issue.

Changing the LED brightness on web or physically on remote makes no difference either.

Can confirm it is the remote charging LED, as it only occurs when the remote is docked after being used for a period of time (remote needs to charge).  Again on both docks.  (one 3M from wifi router, one in another room)

Some sort of bug with the docks returning to 66% brightness and the setting to 0% not saving.  (even if I change in web configurator, reboot remote, clear web cache and login via web config.  Reports 66% brightness...

Is there a recovery for the remote, I can boot to, so I can format flash and reinstall v1 firmware or something?

"status LED off" setting would be amazing.
Maybe a dark/night node or something

I currently have a ugly child plaster over led in the bedroom (pleister/verband) :-(

**Comment by zehnm** [comment] 2023-11-20 10:19
@smarthomesydney The dock LED brightness is not influenced by the remote firmware. This is fully controlled by the dock. Going back to an older remote firmware wouldn't change the behaviour.

The 66% is an open display issue (#178).
I will keep both issues open and we'll fix it in one go: "full off" and displaying the correct value in the web-configurator & UI.

**Comment by smarthomesydney** [comment] 2023-11-20 11:31
Thanks mate.

**Comment by zehnm** [comment] 2024-02-07 20:55
New dock firmware is almost ready and should be released within a week after some more testing. Brightness 0 now disables status & etherned LEDS, except for setup, identify, ota and configuration reset events.

**Comment by zehnm** [comment] 2024-03-13 21:29
Fixed in 1.7.4

**Closed by zehnm** 2024-03-13 21:29 UTC
Labels: bug, dock
