### ISSUE TITLE
[bug] Marantz Generic AVR 1 IR set running into Bad request error

### ISSUE THREAD

**Issue by Armadill0** [unfoldedcircle/feature-and-bug-tracker#26] opened 2023-09-06 22:23 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

I just created a remote in the webconfigurator of my UCR2 from the brand "Marantz" where I selected the "Generic AVR 1" device.

As soon as I try to send any command I only get an error saying "Bad request" on the remote. Tested it with my second UCR2 and two different docks. Always the same result.

Other IR sets for different devices and a custom learned one is working flawlessly. So my best guess is that it has to do with the actual selected IR set when the Remote is telling the dock to send a command.

### How to Reproduce

1. Go to UCR2 webconfigurator and login
2. Click the burger menu icon and select "Remotes" item
3. Click the "+"-Button to add a new remote
4. name field can be left empty
5. Select "Marantz" as manufacturer and "Generic AVR 1" as the device
6. Select the dock which should send the IR commands and click "Next" to finally create the remote
7. Click the burger menu icon again and select "User Interface"
8. Select a Profile
9. Search the "Generic AVR 1" entity from the list on the right and add it to a page
10. Take the remote, navigate to the page where you added the entity
11. Select the entity and long press OK button to enter the remote functionality
12. Press any physical key or any function from the screen
13. You will always end up with a "Bad request" error

### Expected behavior

Execute the IR command which has been requested.

### System version

v1.1.1

### What part of the system affected by the problem?

Core

**Comment by Armadill0** [comment] 2023-09-06 22:41
I just created remotes with the other Marantz devices. All have the same issue. Every command only gets the "Bad request" error.

**Comment by ijsklont** [comment] 2023-09-09 10:55
I don't know if it is useful to mention here, however I have been able  to replicate the exact same issue myself.

**Comment by RomRider** [comment] 2023-09-22 17:46
Still the same issue with version 1.2.1

**Comment by zehnm** [comment] 2023-09-22 20:38
Found the issue: most Marantz PRONTO codes consist of two PRONTO codes, which are not correctly separated and then trigger an invalid IR command code.
The very few "single codes" like INPUT_10 work, but the majority in the dataset don't.

This will be fixed next week, and we'll verify the Marantz codes if they are correct.

**Comment by ijsklont** [comment] 2023-09-22 20:51
That would also then fully explain why even manually learning some codes doesn't work.

Great to see you found the cause! Eagerly waiting for the fix next week 😁

**Comment by zehnm** [comment] 2023-10-12 21:00
Part of the BETA group release 1.4.0 and included in next public release.

**Comment by zehnm** [comment] 2023-10-16 20:20
Fixed in 1.4.1

**Closed by zehnm** 2023-10-16 20:20 UTC
Labels: bug, core

**Comment by Armadill0** [comment] 2024-02-04 14:30
@zehnm Hi Markus, unfortunately I am experiencing the same problem since update 1.6.0 and it's still there with current1.6.7. Would you like to reopen this issue or should I create a new one instead?

Nvm opened a new one. :)
